version: '3.8'

services:
  backend:
    image: instagramCopy/api
    ports:
      - "5443:8080"
    depends_on:
      - mssql
      - mongodb

  frontend:
    image: instagramCopy/web
    ports:
      - "80:4443"
    depends_on:
      - backend

  worker:
    image: instagramCopy/worker
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
