global:
  scrape_interval: 10s # How often Prometheus will scrape the targets.

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dotnet-api" # Name of your job (can be any string).
    metrics_path: /metrics # The metrics path defined by `app.MapMetrics();`
    scrape_interval: 15s
    scheme: "http"
    static_configs:
      - targets: ["host.docker.internal:5011"]
    tls_config:
      insecure_skip_verify: true # Ignore TLS verification
